uploads = []
generated = []

[[outputs]]
id = "FdFKaxDHIYTUFYqE4ghVh"
uri = "file://docs/StoreFrontAdminUserGuide.md"
type = "text"
title = "StoreFront Admin User Guide"

[[outputs]]
id = "5rMRQiIPRL-Wx1MREyDDA"
uri = "file://docs/white-labeling.md"
type = "text"
title = "White-Labeling Architecture (updated)"

[[outputs]]
id = "XXE1gZsy5XoMJZp-J4Idd"
uri = "file://docs/mobile.md"
type = "text"
title = "Mobile Navigation Documentation"

[[outputs]]
id = "9CzbHIErSCj8wFFK3DueU"
uri = "file://docs/form-submission.md"
type = "text"
title = "Quote Form Submission — Implementation Reference"

[[outputs]]
id = "8cF-k2acBCDlkPjREHAAu"
uri = "file://page-management-system.zip"
type = "unspecified"
title = "Page Management System"

[[outputs]]
id = "iXF0_M6tzGiP8-qPR-lDb"
uri = "file://email-mailable-system.zip"
type = "unspecified"
title = "Email Mailable System"
